#!/bin/bash

# Auto-Build Environment Setup
# Teaouse Design System Implementation
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Teaouse Storefront Development Environment"
echo "========================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking environment..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js 18+${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found${NC}"
    exit 1
fi
echo -e "${GREEN}npm: $(npm --version)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ ! -d "node_modules" ]; then
    npm install
else
    echo "Dependencies already installed"
fi

# ============================================
# ENVIRONMENT VARIABLES
# ============================================

echo ""
echo "Checking environment variables..."

if [ ! -f ".env.local" ] && [ ! -f ".env" ]; then
    if [ -f ".env.template" ]; then
        echo -e "${YELLOW}Creating .env.local from template...${NC}"
        cp .env.template .env.local
        echo -e "${YELLOW}Please update .env.local with your Medusa backend URL${NC}"
    else
        echo -e "${YELLOW}Warning: No .env file found. Create .env.local with NEXT_PUBLIC_MEDUSA_BACKEND_URL${NC}"
    fi
else
    echo -e "${GREEN}Environment file found${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Kill any existing process on port 8000
if lsof -ti:8000 > /dev/null 2>&1; then
    echo "Stopping existing process on port 8000..."
    kill $(lsof -ti:8000) 2>/dev/null || true
    sleep 2
fi

# Start Next.js dev server in background
npm run dev &
DEV_PID=$!

# Wait for service to be ready
wait_for_service 8000 "Next.js Storefront"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Development Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Storefront: http://localhost:8000"
echo ""
echo "Key Pages to Verify:"
echo "  Homepage:  http://localhost:8000/"
echo "  Store:     http://localhost:8000/store"
echo "  Account:   http://localhost:8000/account"
echo "  Cart:      http://localhost:8000/cart"
echo ""
echo "Dev server PID: $DEV_PID"
echo ""
echo "To stop: kill $DEV_PID"
echo ""
echo "========================================"
echo "Design System Implementation Spec 001"
echo "========================================"
echo ""
echo "Phases:"
echo "  1. Design Foundation (tailwind.config.js, layout.tsx, globals.css)"
echo "  2. Layout Components (nav, footer, hero, side-menu)"
echo "  3. UI Components (cards, forms, modals, buttons)"
echo "  4. Integration Verification"
echo ""
echo "Total Subtasks: 14"
echo "Recommended Parallel Workers: 2"
echo ""
